version: 1
project:
  name: null
paths:
  sgconfig: sgconfig.yml
  project_rules: .byor/rules/project
  personal_local_rules: .byor/rules/personal/local
  personal_global_rules: .byor/rules/personal/global
checks: []
